apiVersion: v1
kind: Secret
metadata:
  name: {{ include "videostreamgo.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "videostreamgo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.platform-api.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.instance-api.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "videostreamgo.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "videostreamgo.labels" . | nindent 4 }}
type: kubernetes.io/tls
